### ISSUE TITLE
Full portrait art

### ISSUE THREAD

**Issue by robertchou91** [EpicSevenDB/apiserver#4]
Some of the full portrait arts are getting the 404 errors. 

https://assets.epicsevendb.com/herofull/armin.png as an example. 
I notice in Angelica and Cidd as well.

**Comment by RaphaelDDL** [comment]
Hi there @robertchou91 

404 on some herofulls are expected at this point. I have set-up the image lazyload code that when an image call gives 404 (aka I don't have the image yet), it'll replace the `img` `src` with the upper-body image - which I have from everyone, example, Armin: https://assets.epicsevendb.com/hero/armin/full.png

I add the herofull images based on [Reddit user WarkoalkA](https://old.reddit.com/user/WarkoalkA/) work. Unfortunately there's no way to directly extract full body images from the game since they are animated with Live2D. So I need to wait for WarkoalkA's edit which (I believe) he edits and clean up from in-game screenshots.

I've been adding the images when WarkoalkA releases more images. Unfortunately it's manual so it'll take a while to have 'em all. 

In the meantime, I've done this 404 lazyload "hack".

Thank you for the report though :)
